baseurl = "https://www.belson-education.co.uk/"
languageCode = "en-us"
title = "Belson Education"
theme = "hugo-coming-soon-theme"


[params]
  # cursive, block
  TitleStyle = "cursive"  
  # Each subtitle element will be displayed as a separate line
	Subtitle = ["The website is coming soon"]

  # counter
  disableCountdown  = false
  countdownYear = "2020"
  countdownMonth = "12"
  countdownDay  = "31"
