baseurl = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-coming-soon-theme"

[params]
  # cursive, block
  TitleStyle = "cursive"
  # black, blue, green, red, orange 
  FilterColor = "black"
  
	Subtitle = "Really awesome time lapse of a beautiful city."
  CallToAction = "Join the waiting list for the beta. We'll keep you posted."
  Action = "Notify Me"
  
  # GoogleAnalytics = "UA-00000000-0"

  # MailChimp
  MailChimpFormAction = "https://mynewhugosite.us15.list-manage.com/subscribe/post?u=a0a0a0a0a0a0a0a0a0a0a0a0a&amp;id=0000000000"
  MailChimpInputName = "b_a0a0a0a0a0a0a0a0a0a0a0a0a_0000000000"
